name: wardrobe
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_cropper: ^1.2.2
  path: ^1.6.4
  sqflite: ^1.3.0
  camera: ^0.5.8+5
  path_provider: ^1.6.9
  bubble_tab_indicator: ^0.1.4
  bubble_bottom_bar: ^1.2.0
  tflite: ^1.1.1
  http: ^0.12.2
  charts_flutter: ^0.9.0

  characters: ^1.0.0
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/model/labels.txt
    - assets/model/model.tflite
    - assets/model/model2.tflite
    - assets/model/colorLabels.txt
    - assets/model/colorModel.tflite
